
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy 
        run: | 
          # install dependencies
          npm install
          # build the website
          npm run build
          # install gh-pages
          npm install gh-pages
          # deploy to GitHub pages
          npm run deploy