
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install our project dependencies
        run: npm install

      - name: Build and deploy
        run: |
          # build the website
          npm run build
          # deploy the website
          npm install -g serve
          serve -s build
